"use client"
import Head from 'next/head';
import '@/styles/globals.css'

import PrelineScript from '@/components/PrelineScript'
import Nav from '@/components/header/NavErase';
import { RecoilRoot } from 'recoil';

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <RecoilRoot>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <html lang="en">
        <body>
          <Nav />
          {children}
        </body>
        <PrelineScript />
      </html>
    </RecoilRoot>
  )
}
