import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import '@/styles/globals.css'

import Script from 'next/script';
import Nav from '@/components/header/NavDaisy'
import Footer from '@/components/footer/BasicFooter'
import PrelineScript from '@/components/PrelineScript'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <Footer />
        <Script
          src="https://hm.baidu.com/hm.js?7ca9eaee1837bb42e470f1949560a9fa"
          strategy="beforeInteractive"
        />
      </body>
      <PrelineScript />
    </html>
  )
}
