import type { Metadata } from 'next'
import '@/styles/globals.css'

import Script from 'next/script';
import PrelineScript from '@/components/PrelineScript'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Script
          src="https://hm.baidu.com/hm.js?7ca9eaee1837bb42e470f1949560a9fa"
          strategy="beforeInteractive"
        />
      </body>
      <PrelineScript />
    </html>
  )
}
