import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import '@/styles/globals.css'

import Nav from '@/components/header/Nav'
import PrelineScript from '@/components/PrelineScript'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
      <PrelineScript />
    </html>
  )
}
